import {
  IconCheck,
  IconChevronLeft,
  IconChevronRight,
  IconDots,
  IconEye,
  IconEyeOff,
  IconFilterFilled,
  IconGripVertical,
  IconInfoCircleFilled,
  IconLayoutSidebarRightCollapse,
  IconPencil,
  IconPlus,
  IconRotateClockwise2,
  IconSortAscending,
  IconSortDescending,
  IconTextWrap,
  IconTrashFilled,
} from "@tabler/icons-react";

export const icons = {
  sortAscending: IconSortAscending,
  sortDescending: IconSortDescending,
  filter: IconFilterFilled,
  wrapText: IconTextWrap,
  visible: IconEye,
  hidden: IconEyeOff,
  previous: IconChevronLeft,
  next: IconChevronRight,
  reset: IconRotateClockwise2,
  dragHandle: IconGripVertical,
  more: IconDots,
  edit: IconPencil,
  info: IconInfoCircleFilled,
  closeRightPage: IconLayoutSidebarRightCollapse,
  delete: IconTrashFilled,
  addField: IconPlus,
  check: IconCheck,
} as const;
